### ISSUE TITLE
Request for a new command

### ISSUE THREAD

**Issue by ToniOfQ** [KartikeSingh/tutorial_bot#2]
Can you please add a command for sending random waifu from MyWaifuList (https://mywaifulist.moe/random) with full details? Example: 
Name - 
Original Name -
Romaji Name -
Appears in -
Place of Origin -
Age - 
Date of Birth -
Height -
Weight -
Blood Type -
Waist -
Bust - 
Hip -
Popularity -
Like -
Trash - 
Description -

**Comment by KartikeSingh** [comment]
I can make a video on that but do they have some kind of API for this?
Like for fetching these details

**Comment by ToniOfQ** [comment]
They do have an API, but it's paid

**Comment by KartikeSingh** [comment]
I see, then I will make a web scraping video, to do it for free :D

**Comment by ToniOfQ** [comment]
ok, thanks

**Comment by KartikeSingh** [comment]
no worrries, thanks a lot for the suggestion.

I will start on the video after I am done with the video I am currently working on ( Timeout in slash commands )

**Comment by UnschooledGamer** [comment]
Close the issue now

**Comment by KartikeSingh** [comment]
I am thinking to close after actually making a video, else I might forget about this

**Comment by UnschooledGamer** [comment]
Ok

**Comment by KartikeSingh** [comment]
looks like they are using protection, so that we can't send get requests to their pages via axios and similar things, I will try adding human like headers and some more stuff

**Comment by NotSoMik** [comment]
I got a new idea about the pokemon list command, if the pokemons exceed 1024 characters the bot will have to add buttons to the message, if you can also show the pokemon icons next to their names it would be great

**Comment by ToniOfQ** [comment]
> looks like they are using protection, so that we can't send get requests to their pages via axios and similar things, I will try adding human like headers and some more stuff

I also had that issue. But when i try to fetch the site from [RunKit](https://npm.runkit.com/axios), it worked.

```js
const axios = require("axios")
const a = async () => {
await axios.get("https://mywaifulist.moe/waifu/kirisaki-chitoge").then((res) => {
return console.log(res)
}).catch((err) => {
return console.log(err)
})
}
a()
```
I didn't run prettier xD

**Comment by KartikeSingh** [comment]
@ToniOfQ I think when we send request from a different ip or maybe by adding some extra headers it might work. I will try to add some dummy headers for testing soon.

**Comment by NotSoMik** [comment]
> I got a new idea about the pokemon list command, if the pokemons exceed 1024 characters the bot will have to add buttons to the message, if you can also show the pokemon icons next to their names it would be great

So can you try to add this? @KartikeSingh

**Comment by ToniOfQ** [comment]
> 

Ok thanks. Btw i've started to learn js (my first programming language) a week ago.

**Comment by KartikeSingh** [comment]
> > 
> 
> Ok thanks. Btw i've started to learn js (my first programming language) a week ago.

wow that's cool, Well I do have a series on JavaScript but I will suggest you to just watch the first episode
well some learning material:
- https://www.w3schools.com/js/default.asp
- https://youtu.be/uVCBMl1-ia4

Also a suggestion, when you learn something try to do different things with that code instead of moving on to the next thing.
example
let's say you learned how to use for loop to print numbers, then try to print Square of numbers and like different stuff, if you do that you won't forget the syntax and stuff.

Also you can join [my discord](https://discord.gg/PBFj276RUw), it is a bit easier to chat there :D

**Comment by ToniOfQ** [comment]
> > > 
> > 
> > 
> > Ok thanks. Btw i've started to learn js (my first programming language) a week ago.
> 
> wow that's cool, Well I do have a series on JavaScript but I will suggest you to just watch the first episode well some learning material:
> 
> * https://www.w3schools.com/js/default.asp
> * https://youtu.be/uVCBMl1-ia4
> 
> Also a suggestion, when you learn something try to do different things with that code instead of moving on to the next thing. example let's say you learned how to use for loop to print numbers, then try to print Square of numbers and like different stuff, if you do that you won't forget the syntax and stuff.
> 
> Also you can join [my discord](https://discord.gg/PBFj276RUw), it is a bit easier to chat there :D

thanks

**Comment by KartikeSingh** [comment]
> I got a new idea about the pokemon list command, if the pokemons exceed 1024 characters the bot will have to add buttons to the message, if you can also show the pokemon icons next to their names it would be great

@rufy545 there you go https://www.youtube.com/watch?v=uGIl0eETaWU

**Comment by ToniOfQ** [comment]
Is it done @KartikeSingh?

**Comment by KartikeSingh** [comment]
@ToniOfQ you mean the waifu command? well we can use https://www.npmjs.com/package/puppeteer for this but it will eat lot of ram

**Comment by ToniOfQ** [comment]
Yes, but are you making it?

**Comment by KartikeSingh** [comment]
sure, I will!

**Comment by ToniOfQ** [comment]
thank you bro

**Comment by KartikeSingh** [comment]
no worries, thanks you for your patience
