### ISSUE TITLE
timer with problem

### ISSUE THREAD

**Issue by ghost** [KartikeSingh/tutorial_bot#4]
well i was testing the system and i found a problem, when you set a reminder, if the time of this reminder is passed and the bot is offline, when you turn on the bot the error, and it does not notify the member

**Comment by KartikeSingh** [comment]
it works fine for me, Please show the error and your code.
Also if it's fine with you we can continue on [discord](https://discord.gg/AdP8h2nvh2).

**Comment by KartikeSingh** [comment]
Closing the ticket due to inactivity.
